---
abstract: 'Create objects from hashes on the fly'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Fatal: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Objectify
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Objectified:
    file: lib/Objectify.pm
    version: 0.001
  Objectify:
    file: lib/Objectify.pm
    version: 0.001
requires:
  Carp: 0
  Class::XSAccessor: 0
  Scalar::Util: 0
  Sub::Install: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Objectify
  homepage: https://github.com/dagolden/objectify
  repository: https://github.com/dagolden/objectify.git
version: 0.001
